update

diff --git a/.github/workflows/check-s3-db-v1.yml b/.github/workflows/check-s3-db-v1.yml
--- a/.github/workflows/check-s3-db-v1.yml
+++ b/.github/workflows/check-s3-db-v1.yml
@@ -21,15 +21,23 @@ jobs:
           python -m pip install --upgrade pip
           pip install boto3
 
+      - name: Validate AWS Region
+        run: |
+          echo "AWS Region: ap-south-1"
+          if [ -z "ap-south-1" ]; then
+            echo "Error: AWS_DEFAULT_REGION is not set."
+            exit 1
+          fi
+
       - name: Configure AWS Credentials
         run: |
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws configure set region ap-south-1
 
-      - name: Run Modify S3 DB Script
+      - name: Run S3 DB Check Script
         run: |
-          python modify_s3_db_script-v1.py
+          python check_s3_db_script-v1.py
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
